<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_dashboard</name>
   <tag></tag>
   <elementGuidId>b870b8b7-746a-4a8f-b6d4-35e3e5082794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'dashboard')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cd38be2-17b8-47c1-8da7-9969ba38ccfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assurestack-dev.dxdyhosting.xyz/dashboard</value>
      <webElementGuid>c9c1f2a8-ef6f-49b2-866d-df57925a5fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> dashboard</value>
      <webElementGuid>fd23376b-42a8-4ef8-8a3c-19bc41eba9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;as-container-fluid&quot;]/div[@class=&quot;as-dashboard-wrapper&quot;]/div[@class=&quot;as-dashboard-wrapper__side-nav nav-show-hide&quot;]/div[@class=&quot;as-side-navigation&quot;]/nav[1]/ul[@class=&quot;dashboard&quot;]/li[1]/a[1]</value>
      <webElementGuid>01dc52eb-3072-4841-8f2b-18357dae7189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'dashboard')]</value>
      <webElementGuid>26532e36-74d7-41c7-a4cd-54ae59e6f6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Notificaions'])[1]/following::a[2]</value>
      <webElementGuid>857a6015-ee9d-4dec-b610-fa47566c9f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::a[5]</value>
      <webElementGuid>0afeaf5f-4cf9-441a-8261-83aa816c565c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[1]/preceding::a[1]</value>
      <webElementGuid>31cfbde3-82ca-4156-ac75-a7dd8fb1baf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::a[2]</value>
      <webElementGuid>d87ed275-2233-45bc-a2c7-8934a85475ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dashboard']/parent::*</value>
      <webElementGuid>8cf6fa89-dff2-4c5d-b27c-edfbc3b1801a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://assurestack-dev.dxdyhosting.xyz/dashboard')]</value>
      <webElementGuid>4e2950b9-cc64-4cd2-97ed-4d685a5b2e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>1120ed9a-1dee-4596-8651-0bb4782ea16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://assurestack-dev.dxdyhosting.xyz/dashboard' and (text() = ' dashboard' or . = ' dashboard')]</value>
      <webElementGuid>76de5998-e236-4362-b9b5-1a1959912558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
