<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assure Stack Text</name>
   <tag></tag>
   <elementGuidId>e07c2904-6674-42b9-b1e0-e3530bf79622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3cdaf4c3-a624-486c-b720-d83afd42a909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>47062b95-8a43-4f60-92f6-b0f25e409f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/logo-small.png</value>
      <webElementGuid>df571878-97d1-4e2a-a063-f2e45477e5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;as-signin-wrapper&quot;]/div[@class=&quot;as-signin-wrapper__banner&quot;]/img[1]</value>
      <webElementGuid>b67f737c-e2cc-4380-aab7-84b759bb38fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='logo']</value>
      <webElementGuid>0fb025f5-ecd1-4ba6-897b-877db60a1c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4626632a-1db1-43c3-8cbe-86b09679667d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'logo' and @src = '/assets/images/logo-small.png']</value>
      <webElementGuid>e4b08570-47c4-446f-8d76-a7da2956f8b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
