<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remember Me Checkbox</name>
   <tag></tag>
   <elementGuidId>546a0bb2-9a5d-4bbf-aca3-59221a7030b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56389237-42e3-4640-90ee-8ec9eca37540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>84d8bf91-3116-4345-b012-ae81df2d3522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model.lazy</name>
      <type>Main</type>
      <value>remember</value>
      <webElementGuid>7f91cf29-f08b-48bb-93de-eb8c9b2c40b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9d0d0caf-2755-40fe-973b-df2b2436ecb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;as-signin-wrapper&quot;]/div[@class=&quot;as-signin-wrapper__form&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form__wrapper&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form__wrapper___form-wrapper&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form__wrapper___form-wrapper___form&quot;]/div[@class=&quot;as-common-form&quot;]/form[1]/div[@class=&quot;as-common-form__input&quot;]/div[@class=&quot;as-common-form__input___switch-error&quot;]/div[@class=&quot;switch&quot;]/input[1]</value>
      <webElementGuid>eabacea2-bdcc-43c4-8235-ce3d546a4b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1']</value>
      <webElementGuid>d8311bee-e610-4f34-b2d9-a0f1ad72bc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>06747400-6f83-424a-ba1d-bf351c3c7598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>fee8e31d-48d6-474d-bc30-902c9d71830f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
