<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox</name>
   <tag></tag>
   <elementGuidId>8b5ecb19-bc17-44b3-b3ed-90fc3d053807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>815f28c5-a1b1-432f-b310-e60dd75c9db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>01462041-aa2b-46e1-b2a4-679cbc24d89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model.lazy</name>
      <type>Main</type>
      <value>terms_and_condition</value>
      <webElementGuid>6ce6b29b-7722-455f-80e4-14246dbcf879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;as-signin-wrapper&quot;]/div[@class=&quot;as-signin-wrapper__form&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form__wrapper&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form__wrapper___form-wrapper&quot;]/div[@class=&quot;as-signin-wrapper__form__scroll-form__wrapper___form-wrapper___form&quot;]/div[@class=&quot;as-common-form&quot;]/form[1]/div[@class=&quot;as-common-form__input&quot;]/div[@class=&quot;as-common-form__input___tearms-conditions&quot;]/section[@class=&quot;as-modal&quot;]/div[1]/div[@class=&quot;as-termcondition-text&quot;]/input[1]</value>
      <webElementGuid>ab364b4b-dda8-41bc-8a11-02de5ce977b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>4a4abb2d-0be9-412d-a36f-b86f00ffe386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/input</value>
      <webElementGuid>f204be43-87d4-4616-a10a-c52e221272ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>294d078c-990b-4782-af48-4d7859f1cbe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
