<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Audits Conducted Bar Chart</name>
   <tag></tag>
   <elementGuidId>ccfe5bc0-4b7b-4769-b1ab-d6758c0ea20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='myChart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myChart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>087c13c8-159c-4987-9348-7d2c241e6eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myChart</value>
      <webElementGuid>b844193c-aaae-4359-9214-bb73e5e9e996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-ref</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>2ae1553a-0ea5-4a69-81d9-c533b600d7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1425</value>
      <webElementGuid>c13bceec-601f-47b2-9341-7cac02b34930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>712</value>
      <webElementGuid>3287dce6-737d-4641-b535-182f594b17ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myChart&quot;)</value>
      <webElementGuid>8810e871-08ed-4a3f-be8d-9fd216caa24d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='myChart']</value>
      <webElementGuid>9abab7be-fd70-42f6-a418-6bd0b3ad3522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>393c5888-e4ab-45cf-b5c4-0b2573ef5277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'myChart']</value>
      <webElementGuid>df7b5ff1-40cb-490b-bb3d-59ef662020fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
