<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hide Filter Button</name>
   <tag></tag>
   <elementGuidId>77a907c1-f87b-4fcd-8cab-b45c9b50d4e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.as-primary-btn.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f929ae0d-f364-419c-84a0-3ea0afecbc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-on:mouseenter</name>
      <type>Main</type>
      <value>tooltip = true</value>
      <webElementGuid>77f5aedb-6e37-4f21-8d93-aa51898e0bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-on:mouseleave</name>
      <type>Main</type>
      <value>tooltip = false</value>
      <webElementGuid>c18634e5-a7fa-4e67-8b45-9cbfd693d488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>as-primary-btn active</value>
      <webElementGuid>8feded59-1b30-4f53-9948-0038703e3e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@click</name>
      <type>Main</type>
      <value>show = !show</value>
      <webElementGuid>c1f444fc-acf3-428b-89aa-a3dda07eff1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:aria-expanded</name>
      <type>Main</type>
      <value>show ? 'true' : 'false'</value>
      <webElementGuid>b952a151-48c9-4e38-9eb5-56c41c4804bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:class</name>
      <type>Main</type>
      <value>{ 'active': show }</value>
      <webElementGuid>db64074d-390b-4a7a-ae6d-ea4c322b9eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b2b6bf30-4504-476a-801a-f4b19481f993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Hide
                            Show
                            Filters
                        </value>
      <webElementGuid>a85bda37-b4d4-46a5-a809-bfcd41d4dcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;as-container-fluid&quot;]/div[@class=&quot;as-dashboard-wrapper&quot;]/div[@class=&quot;as-dashboard-wrapper__main-content&quot;]/div[@class=&quot;as-reports&quot;]/div[@class=&quot;as-reports__filter-section&quot;]/div[1]/div[@class=&quot;as-hover&quot;]/button[@class=&quot;as-primary-btn active&quot;]</value>
      <webElementGuid>6c5c5efc-6f9f-4134-9de4-af98bb73f6ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/following::button[1]</value>
      <webElementGuid>16e08e1a-3881-4683-b1d6-58883b56a69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/following::button[1]</value>
      <webElementGuid>8f89f61b-651c-48ab-b0ab-0126399dd278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>287b9942-1abf-4830-bbef-de47d7c008da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>d6229342-5dac-40e0-b07d-390a436d3f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                            Hide
                            Show
                            Filters
                        ' or . = '
                            Hide
                            Show
                            Filters
                        ')]</value>
      <webElementGuid>3d54aa06-ee1d-40c2-a6eb-7bbaeb67f716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
