<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Inspections Performance Bar Chart</name>
   <tag></tag>
   <elementGuidId>18ae223e-b180-460e-98de-512a9af34bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='performance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#performance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>a26db9bb-8cc5-49a0-be37-8793bbc3dbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>performance</value>
      <webElementGuid>1b01a4f6-0833-4b2b-a0ec-04fbf786974c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-ref</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>317cd2c9-512b-426f-b2f7-3fd7e7751bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1425</value>
      <webElementGuid>f3f48185-ac3d-4641-b672-cd1e1597732f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>712</value>
      <webElementGuid>eea43a5d-ce03-49fb-9711-130dbe310d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;performance&quot;)</value>
      <webElementGuid>fbd4bc4e-fb45-41c5-baf5-da5e15646cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='performance']</value>
      <webElementGuid>c3361427-102b-4bd9-af12-d5430014a690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/canvas</value>
      <webElementGuid>36534fe2-0bc4-4112-adc5-47d891b5769d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'performance']</value>
      <webElementGuid>20c09109-1b15-43e8-9766-7dc7736d6e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
