<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Inspections Performance Line Chart</name>
   <tag></tag>
   <elementGuidId>6350fdf2-f0b2-4c79-afe0-1a76425ba4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/div/div[4]/div/div[2]/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myChart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>78dd9827-ac5c-40da-aa00-cd65e7e0d98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myChart</value>
      <webElementGuid>9a6bd8c6-7d4e-4666-b581-3dccc65ccfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-ref</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>b3edeba6-3899-47d1-aae1-e9bd93771df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1425</value>
      <webElementGuid>9fab7a3c-dd68-459e-9746-a58095c33592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>712</value>
      <webElementGuid>3591c785-4f63-42b0-931b-c86ff20abcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myChart&quot;)</value>
      <webElementGuid>93b1c3f4-02cb-47f4-9d56-9c3b6c6303fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='myChart']</value>
      <webElementGuid>869ec3e2-cb15-4bbd-89ff-3c4117f3cf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>18c45a71-82aa-4879-a149-362132312993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'myChart']</value>
      <webElementGuid>ae0c8d78-dba6-4faf-8385-29576d7e2d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
