<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Line Chart</name>
   <tag></tag>
   <elementGuidId>6fed1b49-611e-4043-b3f3-7a20165c3846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myChart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/div/div[3]/div/div[2]/div/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>e78a25af-5dc1-4487-9ff6-63ea769f0657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myChart</value>
      <webElementGuid>6d28cdc5-a431-43d3-9c44-b154616cc373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-ref</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>4a295173-38b8-403e-97d6-a5d098b26c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1425</value>
      <webElementGuid>86734e71-1ea5-4c3d-ad47-ec76e837dbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>712</value>
      <webElementGuid>1b7d5782-672c-40c7-84a7-927ca7075598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myChart&quot;)</value>
      <webElementGuid>a5cbf435-8551-47c9-9498-71f06b93c552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='myChart']</value>
      <webElementGuid>ad5d50b1-8525-4bd8-b938-2f3b4f77e862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>66424e5e-6366-4c11-816b-de65efd13746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'myChart']</value>
      <webElementGuid>a4ecebfc-de7e-419b-9f23-58b5fd422cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
