<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK_flatpickr-next-month</name>
   <tag></tag>
   <elementGuidId>99d04b6e-b652-4a19-b597-3d5a2931fe3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flatpickr-next-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d22a506-2f49-4a66-bb50-4addf0639d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flatpickr-next-month</value>
      <webElementGuid>60f4291d-be69-45ca-945b-be173272bb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flatpickr-calendar rangeMode animate open arrowTop arrowLeft&quot;]/div[@class=&quot;flatpickr-months&quot;]/span[@class=&quot;flatpickr-next-month&quot;]</value>
      <webElementGuid>3bbf7296-8b3d-48ca-8887-f686b4659101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::span[4]</value>
      <webElementGuid>f4b42986-b21e-4858-99ac-5b2242d1096f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you own this website?'])[1]/following::span[4]</value>
      <webElementGuid>89703b7e-fdb3-42ff-8a91-6678c3d6fdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/preceding::span[1]</value>
      <webElementGuid>30cbace9-5505-4e56-9ec8-45e39df4848f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/preceding::span[2]</value>
      <webElementGuid>f531c08f-cd3b-400e-bf94-944b900f6d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
      <webElementGuid>4f894e9e-d7d6-46ad-bdb1-4fb470c52d2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
